### ISSUE TITLE
vswitch exit with crash.

### ISSUE THREAD

**Issue by danieldin95** [danieldin95/openlan-go#11]
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 INFO Neighbors.AddNeighbor: update d4:4d:a4:90:1b:ae,192.168.1.119,47.56.173.255:57194.
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 INFO Neighbors.AddNeighbor: update d4:4d:a4:90:1b:ae,192.168.1.119,47.56.173.255:57194.
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 INFO Neighbors.AddNeighbor: update d4:4d:a4:90:1b:ae,192.168.1.119,47.56.173.255:57194.
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 INFO Neighbors.AddNeighbor: update d4:4d:a4:90:1b:ae,192.168.1.119,47.56.173.255:57194.
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 INFO Neighbors.AddNeighbor: update d4:4d:a4:90:1b:ae,192.168.1.119,47.56.173.255:57194.
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: 2019/11/12 23:14:56 ERROR TcpWorker.GoLoop: dropping by unAuth
Nov 12 23:14:56 151 bash: panic: runtime error: invalid memory address or nil pointer dereference
Nov 12 23:14:56 151 bash: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x696dc1]
Nov 12 23:14:56 151 bash: goroutine 3571 [running]:
Nov 12 23:14:56 151 bash: container/list.(*List).remove(...)
Nov 12 23:14:56 151 bash: /usr/lib/golang/src/container/list/list.go:111
Nov 12 23:14:56 151 bash: container/list.(*List).Remove(...)
Nov 12 23:14:56 151 bash: /usr/lib/golang/src/container/list/list.go:143
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/libol.(*Logger).SaveError(0xdd6880, 0xc0008a0ae0, 0x26, 0xc0000adc10, 0x1, 0x1)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/libol/logger.go:77 +0xb1
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/libol.(*Logger).Info(0xdd6880, 0x877f4d, 0x21, 0xc0000adc10, 0x1, 0x1)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/libol/logger.go:38 +0xde
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/libol.Info(...)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/libol/logger.go:98
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/vswitch/app.(*Neighbors).AddNeighbor(0xc0000216b0, 0xc0006deaa0)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/vswitch/app/neighbors.go:98 +0x129
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/vswitch/app.(*Neighbors).OnFrame(0xc0000216b0, 0xc0001fe360, 0xc000705f00, 0x0, 0x0)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/vswitch/app/neighbors.go:85 +0x420
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/vswitch.(*WorkerBase).onHook(0xc000081520, 0xc0001fe360, 0xc0007ca000, 0x3c, 0x1000, 0x2, 0xf6)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/vswitch/worker.go:149 +0x124
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/vswitch.(*WorkerBase).OnRecv(0xc000081520, 0xc0001fe360, 0xc0007ca000, 0x3c, 0x1000, 0x1, 0xc000705ec0)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/vswitch/worker.go:169 +0x157
Nov 12 23:14:56 151 bash: github.com/lightstar-dev/openlan-go/libol.(*TcpServer).GoRecv(0xc0000e6150, 0xc0001fe360, 0xc0006f52c0)
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/libol/tcpserver.go:138 +0x254
Nov 12 23:14:56 151 bash: created by github.com/lightstar-dev/openlan-go/libol.(*TcpServer).GoLoop
Nov 12 23:14:56 151 bash: /root/go/src/github.com/lightstar-dev/openlan-go/libol/tcpserver.go:109 +0x3c3
Nov 12 23:14:56 151 kernel: br-olan: port 2(tap0) entered disabled state
Nov 12 23:14:56 151 kernel: device tap0 left promiscuous mode
Nov 12 23:14:56 151 kernel: br-olan: port 2(tap0) entered disabled state
Nov 12 23:14:56 151 kernel: br-olan: port 3(tap1) entered disabled state

**Comment by danieldin95** [comment]
List on logger isn't safe with multiple threading.
