### ISSUE TITLE
vswitch out of memory

### ISSUE THREAD

**Issue by danieldin95** [danieldin95/openlan-go#18]
Jan  7 15:18:01 iZj6c2dcog2gsp1a3kyo2bZ bash: 2020/01/07 15:18:01 ERROR TcpWorker.GoLoop: dropping by unAuth
Jan  7 15:18:03 iZj6c2dcog2gsp1a3kyo2bZ bash: 2020/01/07 15:18:03 ERROR TcpWorker.GoLoop: dropping by unAuth
Jan  7 15:18:04 iZj6c2dcog2gsp1a3kyo2bZ bash: fatal error: runtime: out of memory
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 1(tap0) entered disabled state
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap0 left promiscuous mode
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 1(tap0) entered disabled state
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 2(tap1) entered disabled state
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap1 left promiscuous mode
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 2(tap1) entered disabled state
Jan  7 15:18:05 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 3(tap2) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap2 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 3(tap2) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 4(tap3) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap3 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 4(tap3) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 6(tap5) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 7(tap6) entered listening state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap5 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 6(tap5) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 7(tap6) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: topology change detected, propagating
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap6 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 7(tap6) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 9(tap8) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap8 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 9(tap8) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 8(tap7) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: device tap7 left promiscuous mode
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ kernel: brol-10002: port 8(tap7) entered disabled state
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime stack:
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.throw(0x85d3d8, 0x16)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/panic.go:617 +0x72
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.sysMap(0xc060000000, 0x4000000, 0xdce498)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mem_linux.go:170 +0xc7
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).sysAlloc(0xdb6140, 0x146000, 0xdb6150, 0xa3)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/malloc.go:633 +0x1cd
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).grow(0xdb6140, 0xa3, 0x0)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mheap.go:1222 +0x42
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).allocSpanLocked(0xdb6140, 0xa3, 0xdce4a8, 0x0)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mheap.go:1150 +0x37f
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).alloc_m(0xdb6140, 0xa3, 0x101, 0x0)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mheap.go:977 +0xc2
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).alloc.func1()
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mheap.go:1048 +0x4c
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.(*mheap).alloc(0xdb6140, 0xa3, 0x7ff663000101, 0x427b70)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/mheap.go:1047 +0x8a
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.largeAlloc(0x145551, 0x450100, 0xc05fe66000)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/malloc.go:1055 +0x99
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.mallocgc.func1()
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/malloc.go:950 +0x46
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.systemstack(0x0)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/asm_amd64.s:351 +0x66
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.mstart()
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/proc.go:1153
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: goroutine 1536 [running]:
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.systemstack_switch()
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/asm_amd64.s:311 fp=0xc0000a1638 sp=0xc0000a1630 pc=0x457e20
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.mallocgc(0x145551, 0x0, 0xc0000a1700, 0x40d192)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/malloc.go:949 +0x872 fp=0xc0000a16d8 sp=0xc0000a1638 pc=0x40d522
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.rawstring(0x145551, 0x0, 0x0, 0x0, 0x0, 0x0)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/string.go:259 +0x4f fp=0xc0000a1708 sp=0xc0000a16d8 pc=0x4476ff
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.rawstringtmp(0x0, 0x145551, 0x7ff67560c008, 0xc000512180, 0x40, 0x846040, 0x2f)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/string.go:123 +0x72 fp=0xc0000a1748 sp=0xc0000a1708 pc=0x4470c2
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.concatstrings(0x0, 0xc0000a1828, 0x2, 0x2, 0xc001f136e0, 0xc000090000)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/string.go:49 +0xae fp=0xc0000a17e0 sp=0xc0000a1748 pc=0x446b4e
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: runtime.concatstring2(0x0, 0xc05fe66000, 0x145522, 0xc001f136e0, 0x2f, 0xc001f136e0, 0x2f)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /usr/lib/golang/src/runtime/string.go:58 +0x47 fp=0xc0000a1820 sp=0xc0000a17e0 pc=0x446dc7
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: github.com/danieldin95/openlan-go/vswitch.(*Http).getIndex(0xc00008e200, 0x80f160, 0xc003219560)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /root/go/src/github.com/danieldin95/openlan-go/vswitch/http.go:265 +0xe10 fp=0xc0000a1a80 sp=0xc0000a1820 pc=0x77be40
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: github.com/danieldin95/openlan-go/vswitch.(*Http).IndexHtml(0xc00008e200, 0x8e93a0, 0xc0000102d0, 0xc0004c4400)
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: /root/go/src/github.com/danieldin95/openlan-go/vswitch/http.go:272 +0x40 fp=0xc0000a1b60 sp=0xc0000a1a80 pc=0x77bf10
Jan  7 15:18:06 iZj6c2dcog2gsp1a3kyo2bZ bash: github.com/danieldin95/openlan-go/vswitch.(*Http).IndexHtml-fm(0x8e93a0, 0xc0000102d0, 0xc0004c4400)

**Comment by danieldin95** [comment]
limit online.
