### ISSUE TITLE
when TcpClient close，TapKernel has crash

### ISSUE THREAD

**Issue by danieldin95** [danieldin95/openlan-go#19]
Feb 14 20:59:38 VM_0_3_centos bash[9620]: 2020/02/14 20:59:38 INFO TcpClient.Close 117.136.45.25:45185
Feb 14 20:59:38 VM_0_3_centos bash[9620]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 14 20:59:38 VM_0_3_centos bash[9620]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6d0250]
Feb 14 20:59:38 VM_0_3_centos bash[9620]: goroutine 15565 [running]:
Feb 14 20:59:38 VM_0_3_centos bash[9620]: github.com/danieldin95/openlan-go/network.(*KernelTap).Close(0xc0005320a0, 0x0, 0x0)
Feb 14 20:59:38 VM_0_3_centos bash[9620]: /root/rpmbuild/SOURCES/openlan-4.2/network/tap_kernel.go:95 +0xb0
Feb 14 20:59:38 VM_0_3_centos bash[9620]: github.com/danieldin95/openlan-go/vswitch.(*Worker).ReadTap(0xc0000ae0c0, 0x97ae60, 0xc0005320a0, 0xc0005da200)
Feb 14 20:59:38 VM_0_3_centos bash[9620]: /root/rpmbuild/SOURCES/openlan-4.2/vswitch/worker.go:153 +0x3ad
Feb 14 20:59:38 VM_0_3_centos bash[9620]: created by github.com/danieldin95/openlan-go/vswitch/app.(*PointAuth).onAuth
Feb 14 20:59:38 VM_0_3_centos bash[9620]: /root/rpmbuild/SOURCES/openlan-4.2/vswitch/app/pointauth.go:110 +0x337

**Comment by danieldin95** [comment]
reneter tap.close when tcpclient close.
